const CHUNK_PUBLIC_PATH = "server/app/page.js";
const runtime = require("../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_66bdff._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__ea5163._.js");
runtime.loadChunk("server/chunks/ssr/src_app_896cde._.js");
runtime.loadChunk("server/chunks/ssr/_da8761._.js");
runtime.loadChunk("server/chunks/ssr/src_app_c7d265._.css");
runtime.loadChunk("server/chunks/ssr/node_modules_16929d._.js");
runtime.loadChunk("server/chunks/ssr/_c954b8._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-icons_rx_index_mjs_95ae95._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-icons_pi_index_mjs_7022dd._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-icons_ri_index_mjs_851175._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-icons_fi_index_mjs_8db138._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-icons_ci_index_mjs_1da407._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-icons_fa_index_mjs_a1beb0._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-icons_lib_b806b5._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_c6ada2._.js");
runtime.getOrInstantiateRuntimeModule("[project]/.next-internal/server/app/page/actions.js [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { METADATA_0 => \"[project]/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/src/app/favicon.ico [app-rsc] (static)\\\" } [app-rsc] (structured image object, ecmascript, Next.js server component)\", MODULE_1 => \"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_3 => \"[project]/src/app/page.tsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH).exports;
